### ISSUE TITLE
Add support for CentOS 7

### ISSUE THREAD

**Issue by ramereth** [osuosl-cookbooks/glusterfs#5]

**Comment by armiller** [comment]
@ramereth Can we merge all of these support x distro into one issue?

**Comment by ramereth** [comment]
@armiller I'd prefer to keep track of them independently.

**Comment by armiller** [comment]
Is there a reason? I think one issue with a checklist makes more sense.

**Comment by ramereth** [comment]
I suppose we could merge them all into one issue.
